const CSV_PATH='data/raw_data.csv';
const TRAFFIC_DIVISOR=1, TRAFFIC_UNIT='TB';
let rows=[], charts={}, activeMap='region';
const specs=[
 {key:'traffic',title:'Total Traffic',unit:'TB',color:'#00BFFF',icon:'◉',source:'Total Traffic(Byte)',format:v=>v.toFixed(3)},
 {key:'dlRetx',title:'DL TCP Retransmission',unit:'%',color:'#20E887',icon:'⟳',source:'Downlink TCP Retransmission Rate(%)',format:v=>v.toFixed(2)+'%'},
 {key:'ulRetx',title:'UL TCP Retransmission',unit:'%',color:'#FF9D00',icon:'◉',source:'Uplink TCP Retransmission Rate(%)',format:v=>v.toFixed(2)+'%'},
 {key:'tcp',title:'TCP Success Rate',unit:'%',color:'#A84CFF',icon:'⬡',source:'TCP Connection Success Rate (Included RST)(%)',format:v=>v.toFixed(2)+'%'},
 {key:'dlLoss',title:'DL Packet Loss',unit:'%',color:'#00BFFF',icon:'✥',source:'Downlink TCP Packet Loss Rate(%)',format:v=>v.toFixed(2)+'%'},
 {key:'ulLoss',title:'UL Packet Loss',unit:'%',color:'#FF168C',icon:'✥',source:'Uplink TCP Packet Loss Rate(%)',format:v=>v.toFixed(2)+'%'},
 {key:'e2e',title:'E2E Delay',unit:'ms',color:'#20E887',icon:'◷',source:'E2E Delay(ms)',format:v=>v.toFixed(0)+' ms'},
 {key:'synAck',title:'SYN ACK-ACK Delay',unit:'ms',color:'#A84CFF',icon:'✥',source:'SYN ACK-ACK Delay(ms)',format:v=>v.toFixed(0)+' ms'},
 {key:'synSyn',title:'SYN-SYN ACK Delay',unit:'ms',color:'#00BFFF',icon:'✥',source:'SYN-SYN ACK Delay(ms)',format:v=>v.toFixed(0)+' ms'}
];
const metricKeys=specs.map(s=>s.source);
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function parseDate(s){const [d,t]=s.split(' '),[m,day,y]=d.split('/').map(Number);return new Date(y,m-1,day,...t.split(':').map(Number));}
function isoDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function fmtDate(d){return d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function metricValue(r,key){const v=Number(r[key]||0);return key==='Total Traffic(Byte)'?v/TRAFFIC_DIVISOR:v}
function unique(field){return [...new Set(rows.map(r=>r[field]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)))}
function fillSelect(id,vals){const el=document.getElementById(id), old=el.value;el.innerHTML='<option value="ALL">All '+(id==='region'?'Region':id==='circle'?'Circle':id==='branch'?'Branch':'Kabupaten')+'</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vals.includes(old))el.value=old}
function setupFilters(){
 const min=rows[0].dt,max=rows[rows.length-1].dt; dateFrom.value=isoDate(min);dateTo.value=isoDate(max); region.innerHTML='<option value="ALL">All Region</option>'+unique('REGION').map(v=>`<option>${esc(v)}</option>`).join(''); refreshDependent();
 ['dateFrom','dateTo','period','region','circle','branch','kabupaten','compare','compareMode'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{if(['region','circle','branch'].includes(id))refreshDependent();update()})); reset.onclick=()=>{dateFrom.value=isoDate(min);dateTo.value=isoDate(max);period.value='15min';region.value=circle.value=branch.value=kabupaten.value='ALL';compare.checked=false;compareMode.value='lastWeek';refreshDependent();update()};
}
function refreshDependent(){
 const r=region.value,c=circle.value,b=branch.value;
 let f=rows.filter(x=>r==='ALL'||x.REGION===r);fillSelect('circle',uniqueFrom(f,'CIRCLE'));f=f.filter(x=>c==='ALL'||x.CIRCLE===c);fillSelect('branch',uniqueFrom(f,'BRANCH'));f=f.filter(x=>b==='ALL'||x.BRANCH===b);fillSelect('kabupaten',uniqueFrom(f,'KABUPATEN'));if(!['ALL',...uniqueFrom(f,'KABUPATEN')].includes(kabupaten.value))kabupaten.value='ALL';
}
function uniqueFrom(arr,field){return [...new Set(arr.map(x=>x[field]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)))}
function filtered(extraShiftDays=0){
 const from=new Date(dateFrom.value+'T00:00:00'),to=new Date(dateTo.value+'T23:59:59');from.setDate(from.getDate()+extraShiftDays);to.setDate(to.getDate()+extraShiftDays);
 return rows.filter(r=>r.dt>=from&&r.dt<=to&&(region.value==='ALL'||r.REGION===region.value)&&(circle.value==='ALL'||r.CIRCLE===circle.value)&&(branch.value==='ALL'||r.BRANCH===branch.value)&&(kabupaten.value==='ALL'||r.KABUPATEN===kabupaten.value));
}
function bucket(r){const p=period.value;if(p==='daily')return isoDate(r.dt);if(p==='hourly'){const d=new Date(r.dt);d.setMinutes(0,0,0);return d.toISOString()}return r.dt.toISOString()}
function aggregate(data){const m=new Map();data.forEach(r=>{const k=bucket(r);if(!m.has(k))m.set(k,{k,n:0});const x=m.get(k);x.n++;metricKeys.forEach(key=>x[key]=(x[key]||0)+metricValue(r,key))});return [...m.values()].sort((a,b)=>a.k.localeCompare(b.k)).map(x=>{metricKeys.forEach(key=>x[key]/=x.n);return x})}
function rgba(hex,a){const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${n>>8&255},${n&255},${a})`}
function drawChart(spec,cur,cmp){const ctx=document.getElementById('ch_'+spec.key).getContext('2d');if(charts[spec.key])charts[spec.key].destroy();const labels=cur.map(x=>new Date(x.k).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})+(period.value==='15min'?' '+new Date(x.k).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):''));const datasets=[{label:'Current',data:cur.map(x=>x[spec.source]),borderColor:spec.color,backgroundColor:rgba(spec.color,.12),borderWidth:2,pointRadius:cur.length<=1?4:1.5,pointHoverRadius:5,tension:.3,fill:true,spanGaps:true}];if(compare.checked&&cmp.length){datasets.push({label:compareMode.value==='lastWeek'?'Compare (Last Week)':'Compare (Previous Period)',data:cmp.map(x=>x[spec.source]),borderColor:spec.color,borderWidth:1.5,borderDash:[6,4],pointRadius:0,tension:.3,fill:false})}charts[spec.key]=new Chart(ctx,{type:'line',data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#74a6ca',maxTicksLimit:8},grid:{color:'rgba(24,85,122,.25)'}},y:{ticks:{color:'#74a6ca',maxTicksLimit:5},grid:{color:'rgba(24,85,122,.25)'}}}}});}
function renderCharts(cur,cmp){const box=document.getElementById('charts');box.innerHTML=specs.map(s=>`<div class="chart-card"><div class="chart-head"><h3>${s.title} (${s.unit})</h3><div class="legend"><b style="color:${s.color}">━━ Current</b>${compare.checked&&cmp.length?` <b style="color:${s.color}">┄┄ Compare</b>`:''}</div></div><canvas id="ch_${s.key}"></canvas></div>`).join('');specs.forEach(s=>drawChart(s,cur,cmp))}
function updateKpis(cur,cmp){const c=cur.length?cur[cur.length-1]:null,prev=cmp.length?cmp[cmp.length-1]:null;document.getElementById('kpis').innerHTML=specs.slice(0,8).map((s,i)=>{const val=c?c[s.source]:0,old=prev?prev[s.source]:null;let delta='';if(old!==null&&old!==0){const d=val-old,p=(d/Math.abs(old))*100;delta=`<div class="delta">${d>=0?'▲':'▼'} ${Math.abs(p).toFixed(2)}%</div><div class="vs">vs ${s.format(old)} (Compare)</div>`}else delta='<div class="delta">● Live</div><div class="vs">Current filtered period</div>';return `<div class="kpi ${['green','orange','purple','pink'][i%4]}"><div class="icon">${s.icon}</div><h3>${s.title}</h3><span class="unit">${s.unit}</span><div class="value">${s.format(val)}</div>${delta}</div>`}).join('')}
function renderTable(data,bodyId='tableBody',headId='tableHead',limit=500){const cols=['15 Minutes','REGION','CIRCLE','BRANCH','KABUPATEN','Total Traffic(Byte)','Downlink TCP Retransmission Rate(%)','Uplink TCP Retransmission Rate(%)','TCP Connection Success Rate (Included RST)(%)','Downlink TCP Packet Loss Rate(%)','Uplink TCP Packet Loss Rate(%)','E2E Delay(ms)','SYN ACK-ACK Delay(ms)','SYN-SYN ACK Delay(ms)'];document.getElementById(headId).innerHTML='<tr>'+cols.map((c,i)=>`<th>${i===0?'DATE / TIME':c.replace('Total Traffic(Byte)','TOTAL TRAFFIC (TB)').replace('Downlink TCP Retransmission Rate(%)','DL RETX (%)').replace('Uplink TCP Retransmission Rate(%)','UL RETX (%)').replace('TCP Connection Success Rate (Included RST)(%)','TCP SUCCESS (%)').replace('Downlink TCP Packet Loss Rate(%)','DL LOSS (%)').replace('Uplink TCP Packet Loss Rate(%)','UL LOSS (%)').replace('SYN ACK-ACK Delay(ms)','SYN ACK-ACK (ms)').replace('SYN-SYN ACK Delay(ms)','SYN-SYN ACK (ms)')}</th>`).join('')+'</tr>';const out=[...data].sort((a,b)=>b.dt-a.dt).slice(0,limit);document.getElementById(bodyId).innerHTML=out.map((r,i)=>`<tr><td>${esc(r['15 Minutes'])}</td><td>${esc(r.REGION)}</td><td>${esc(r.CIRCLE)}</td><td>${esc(r.BRANCH)}</td><td>${esc(r.KABUPATEN)}</td><td class="num">${(Number(r['Total Traffic(Byte)'])/TRAFFIC_DIVISOR).toFixed(6)}</td><td class="num">${Number(r['Downlink TCP Retransmission Rate(%)']).toFixed(2)}</td><td class="num">${Number(r['Uplink TCP Retransmission Rate(%)']).toFixed(2)}</td><td class="num">${Number(r['TCP Connection Success Rate (Included RST)(%)']).toFixed(2)}</td><td class="num">${Number(r['Downlink TCP Packet Loss Rate(%)']).toFixed(2)}</td><td class="num">${Number(r['Uplink TCP Packet Loss Rate(%)']).toFixed(2)}</td><td class="num">${Number(r['E2E Delay(ms)']).toFixed(0)}</td><td class="num">${Number(r['SYN ACK-ACK Delay(ms)']).toFixed(0)}</td><td class="num">${Number(r['SYN-SYN ACK Delay(ms)']).toFixed(0)}</td></tr>`).join('');return out}
function update(){const cur=aggregate(filtered()),cmp=compare.checked?aggregate(filtered(compareMode.value==='lastWeek'?-7:-Math.max(1,Math.ceil((new Date(dateTo.value)-new Date(dateFrom.value))/86400000+1)))):[];updateKpis(cur,cmp);renderCharts(cur,cmp);renderTable(filtered());}
function renderMap(){const term=(mapSearch.value||'').toLowerCase();let field=activeMap==='region'?'REGION':activeMap==='circle'?'CIRCLE':activeMap==='branch'?'BRANCH':'KABUPATEN';const vals=unique(field).filter(v=>String(v).toLowerCase().includes(term)).slice(0,40);mapList.innerHTML=vals.map(v=>{const n=rows.filter(r=>r[field]===v).length;return `<div class="map-item"><b>${esc(v)}</b><span>${n.toLocaleString()}</span></div>`}).join('');const regs=unique('REGION').slice(0,12);regionPerformance.innerHTML=regs.map(v=>{const a=rows.filter(r=>r.REGION===v);const perf=avg(a.map(r=>Number(r['TCP Connection Success Rate (Included RST)(%)'])));return `<div class="perf"><span>${esc(v)}</span><b>${perf.toFixed(1)}%</b><div class="bar"><i style="width:${Math.min(100,perf)}%"></i></div></div>`}).join('');const reg=regs.slice(0,8);topologyCanvas.innerHTML=reg.map((v,i)=>`<div class="node" style="left:${8+(i%4)*24}%;top:${18+Math.floor(i/4)*42}%"><span class="dot"></span><strong>${esc(v)}</strong><small>${rows.filter(r=>r.REGION===v).length.toLocaleString()} records</small></div>`).join('');}
function download(){const blob=new Blob([Papa.unparse(filtered())],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sqm_filtered_data.csv';a.click();URL.revokeObjectURL(a.href)}
function initNav(){document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const view=btn.dataset.view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById(view+'View').classList.add('active-view');if(view==='map')renderMap();if(view==='data'){renderTable(rows,'dataBody','dataHead',1000);dataCount.textContent=rows.length.toLocaleString()+' records'}})}
Papa.parse(CSV_PATH,{download:true,header:true,skipEmptyLines:true,dynamicTyping:true,complete:res=>{rows=res.data.filter(r=>r['15 Minutes']).map(r=>({...r,dt:parseDate(String(r['15 Minutes']))})).sort((a,b)=>a.dt-b.dt);setupFilters();update();initNav();renderTable(rows,'dataBody','dataHead',1000);mapSearch.oninput=renderMap;document.querySelectorAll('.map-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.map-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeMap=b.dataset.map;renderMap()});downloadCsv.onclick=download;downloadCsv2.onclick=download;dataSearch.oninput=()=>{const q=dataSearch.value.toLowerCase();renderTable(rows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q))),'dataBody','dataHead',1000)};setInterval(()=>{clock.textContent=new Date().toLocaleTimeString('en-GB',{hour12:false})},1000);}});



